verbosity: verbose
thermal_gaps:
  between_experiments: 5.0
  between_cycles: 60.0
docker:
  strategy: ephemeral
  warmup_delay: 0.0
  auto_teardown: true
notifications:
  webhook_url: https:// test
  on_complete: false
  on_failure: false
results_dir: results
